// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqegdutkjmswrwgmloac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZWdkdXRram1zd3J3Z21sb2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTc1ODgsImV4cCI6MjA2MzgzMzU4OH0.3x-Wy7nRUX2MfxTxABJu1XB0WDxeifsBlXZqjM3ewVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);